export const TrendingQuizzesStyles = {
    container: 'mb-20 px-4',
    headingContainer: 'flex items-center gap-3 mb-8',
    heading: 'text-3xl font-extrabold bg-gradient-to-r from-pink-500 to-indigo-500 text-transparent bg-clip-text',
    filterContainer: 'flex flex-wrap items-center gap-4 mb-6',
    input: 'p-2 w-60 border border-gray-300 dark:border-gray-600 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-pink-500 dark:bg-gray-900 dark:text-white',
    select: 'p-2 border rounded-lg dark:bg-gray-900 dark:text-white',
    numberInput: 'p-2 w-32 border border-gray-300 rounded-lg dark:bg-gray-900 dark:text-white',
    cardGrid: 'grid sm:grid-cols-2 lg:grid-cols-3 gap-6',
    card: 'relative rounded-xl overflow-hidden shadow-lg text-white p-5',
    liveIndicator: 'absolute top-4 right-4 flex items-center gap-1',
    liveDotContainer: 'w-2.5 h-2.5 bg-red-400 rounded-full animate-ping absolute',
    liveDot: 'w-2.5 h-2.5 bg-red-500 rounded-full relative',
    liveText: 'text-sm ml-2 font-semibold',
    cardContent: 'relative z-10 flex flex-col h-full justify-between space-y-4 mt-4',
    cardTitle: 'text-xl font-bold tracking-wide',
    cardInfo: 'flex gap-2 flex-wrap items-center',
    categoryBadge: 'text-xs bg-white/30 px-3 py-1 rounded-full',
    difficultyBadge: 'text-xs bg-black/20 px-3 py-1 rounded-full',
    daysLeft: 'text-sm text-white/80',
    button: 'mt-auto px-4 py-2 bg-white text-indigo-600 font-semibold rounded-full shadow hover:bg-gray-100 transition',
    showMoreButton: 'px-6 py-2 bg-indigo-600 text-white font-semibold rounded-full shadow hover:bg-indigo-700 transition',
  };
  